### PR TITLE
refactor to use deno lsp server

### PR DESCRIPTION
**Pull request by buttercubz**

### CODE REVIEW

**Comment by marc2332** [comment]
Is it ready?

**Comment by buttercubz** [comment]
@marc2332 it's ready

**Comment by marc2332** [comment]
It's working as expected except it says I don't have Deno installed:

image

After looking through the code I have seen you expect a folder with ".deno" to be in my PATH env variable ( which doesn't, that why it gives the error)

I can ensure I have deno installed 😅

**Comment by buttercubz** [comment]
> It's working as expected except it says I don't have Deno installed:
> 
> image
> 
> After looking through the code I have seen you expect a folder with ".deno" to be in my PATH env variable ( which doesn't, that why it gives the error)
> 
> I can ensure I have deno installed

are you using windows, linux or macOs?

**Comment by marc2332** [comment]
> > It's working as expected except it says I don't have Deno installed:
> > 
> > image
> > 
> > After looking through the code I have seen you expect a folder with ".deno" to be in my PATH env variable ( which doesn't, that why it gives the error)
> > 
> > I can ensure I have deno installed
> 
> are you using windows, linux or macOs?

Windows 10 😅

**Pull request closed without merging**
